name: Execute workflow only upon repository initialisation

on:
  push:
    branches:
      - '**'
 
jobs:
    - name: Test
      shell: bash
      run: |
        echo "Hello, world!"
    - name: Disable this workflow
      shell: bash
      run: |
        gh workflow disable -R $GITHUB_REPOSITORY "${{ github.workflow }}"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
